version: "3.5"

services:
  database:
    container_name: database
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_USER: ftpias
      MYSQL_ROOT_PASSWORD: jaPKRQpHJFmaXD4j
    networks:
      red:
        aliases:
          - "database"
    expose:
      - 3306
    ports:
      - 3318:3306
    volumes:
      - ./data:/var/lib/mysql

  redynet:
    container_name: redynet
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    networks:
      red:
        aliases:
          - redynet
    expose:
      - 80
    ports:
      - 3012:80
    working_dir: /var/www/html/
    volumes:
      - $PWD/.:/var/www/html/

networks:
  red:
    driver: bridge